# Logging and Paths
wandb_proj: NoSigmoidTest # Weights and Biases project to log results to.
wandb_save: True # Whether or not to log to Weights and Biases.
log_file: ./logs/scratch_testing.log # Location of log file
model_save_dir: ./best_models # Location to save best models
data_cache_dir: ./datasets # Location of downloaded data (use `conplex_dti download`)

# Misc
device: 0 # CUDA device to use for training
replicate: 0 # Random seed
verbosity: 3 # Verbosity level for logging

prot_glycan_root: ./data
train_path: ./data/train/prot_glycan_train_zscore.csv
val_path: ./data/valid/prot_glycan_valid_zscore.csv
test_path: ./data/test/prot_glycan_test_zscore.csv

num_hidden_layers: 1 # Number of hidden layers in projection to co-embedding space
dropout: 0.2 # Dropout rate in projection to co-embedding space
lambda_spearman: 0.5 # Weight for spearman loss component
coattention: True # Whether to use coattention between protein and glycan embeddings

# Training
epochs: 100 # Number of epochs to train for
batch_size: 128 # Size of batch for binary data set
gradient_accumulation_steps: 1 # Number of steps to accumulate gradients over

early_stopping: 
  enabled: True # Whether to use early stopping
  patience: 15 # Number of epochs with no improvement after which training will be stopped
  metric: "spearmanp"

shuffle: True # Whether to shuffle training data before batching
num_workers: 2 # Number of workers for PyTorch DataLoader
every_n_val: 1 # How often to run validation during training (epochs)
eval_metric: [ "spearmanp", "aupr", "auroc", "mse"] # Metrics to evaluate on during validation
## Learning Rate
lr: 1e-7 # Learning rate for binary training